routes:
  - path: /vercel-docs
    target: https://vercel.com/docs
  - path: /nextjs
    target: https://nextjs.org/
  - path: /piston
    target: https://emkc.org/api/v2/piston
  - path: /github
    target: https://github.com
